In [1]:
from sklearn.datasets import load_iris

In [2]:
import pandas as pd

In [3]:
iris=load_iris()

In [4]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
data=pd.DataFrame(iris.data)

In [6]:
data.shape

(150, 4)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
model=LinearRegression()

In [10]:
dt=data[[0,1]]
dt

0    1
0    5.1  3.5
1    4.9  3.0
2    4.7  3.2
3    4.6  3.1
4    5.0  3.6
..   ...  ...
145  6.7  3.0
146  6.3  2.5
147  6.5  3.0
148  6.2  3.4
149  5.9  3.0

[150 rows x 2 columns]

In [11]:
X=data[[0]]

In [12]:
X

0
0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
..   ...
145  6.7
146  6.3
147  6.5
148  6.2
149  5.9

[150 rows x 1 columns]

In [13]:
y=data[[2]]
y

2
0    1.4
1    1.4
2    1.3
3    1.5
4    1.4
..   ...
145  5.2
146  5.0
147  5.2
148  5.4
149  5.1

[150 rows x 1 columns]

In [14]:
model.fit(X,y)

LinearRegression()

In [15]:
model.predict([[6]])

array([[4.0491545]])

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=0)

In [17]:
model=LinearRegression()
model.fit(X_train,y_train)
y_predict=model.predict(X_test)

In [18]:
from sklearn.metrics import r2_score
r2_score(y_test,y_predict)

0.6666500732314495

In [19]:
Score=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=i)
    model=LinearRegression()
    model.fit(X_train,y_train)
    y_predict=model.predict(X_test)
    Score.append([r2_score(y_test,y_predict),i])
max(Score)

[0.9238770333532589, 840]

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=840)
model=LinearRegression()
model.fit(X_train,y_train)
y_predict=model.predict(X_test)
y_test


2
63   4.7
19   1.5
47   1.4
42   1.3
67   4.1
107  6.3
120  5.7
111  5.3
20   1.7
78   4.5
37   1.4
118  6.9
99   4.1
133  5.1
29   1.6

In [21]:
y_predict


array([[4.23214566],
       [2.38842367],
       [1.46656267],
       [1.09781827],
       [3.67902906],
       [6.44461206],
       [5.70712326],
       [4.78526226],
       [2.94154027],
       [4.04777346],
       [2.01967927],
       [7.18210085],
       [3.49465686],
       [4.60089006],
       [1.65093487]])

In [22]:
t = list(zip(y_test.to_numpy(), y_predict))
t

[(array([4.7]), array([4.23214566])),
 (array([1.5]), array([2.38842367])),
 (array([1.4]), array([1.46656267])),
 (array([1.3]), array([1.09781827])),
 (array([4.1]), array([3.67902906])),
 (array([6.3]), array([6.44461206])),
 (array([5.7]), array([5.70712326])),
 (array([5.3]), array([4.78526226])),
 (array([1.7]), array([2.94154027])),
 (array([4.5]), array([4.04777346])),
 (array([1.4]), array([2.01967927])),
 (array([6.9]), array([7.18210085])),
 (array([4.1]), array([3.49465686])),
 (array([5.1]), array([4.60089006])),
 (array([1.6]), array([1.65093487]))]

In [23]:
from sklearn.model_selection import cross_validate
import numpy as np
result=cross_validate(model,X,y,cv=10,return_train_score=True)
result

{'fit_time': array([0.00383425, 0.00401163, 0.00093389, 0.00137472, 0.        ,
        0.        , 0.00141191, 0.00693417, 0.00653362, 0.00963545]),
 'score_time': array([0.00573516, 0.0047555 , 0.00482726, 0.        , 0.00853109,
        0.008255  , 0.00793672, 0.00115633, 0.        , 0.        ]),
 'test_score': array([-48.70474318, -35.96936401, -37.11257576,   0.63181963,
         -1.73491911,  -1.62498012,  -0.12113027,  -0.92442501,
         -1.02139598,  -4.20836874]),
 'train_score': array([0.73827398, 0.75947774, 0.7417545 , 0.76744855, 0.77092916,
        0.77335513, 0.77514957, 0.75363714, 0.74689809, 0.7554018 ])}

###### 